services:
  api:
    build:
      context: ./TravelMapGuide.Server
      dockerfile: Dockerfile
    ports:
      - "7018:7018"
    networks:
      - app-network
      
  webclient:
    build:
      context: ./TravelMapGuide.Web.Client/Front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - webclient
  #     - api
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
